apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "pm2-on-premise.digesters.fullname" . }}
  labels:
    app: {{ template "pm2-on-premise.digesters.fullname" . }}
    chart: {{ template "pm2-on-premise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "pm2-on-premise.digesters.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "pm2-on-premise.digesters.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.digesters.name }}
          image: "{{ .Values.imageApi }}:{{ .Values.imageTagApi }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          command:
            - node
          args:
            - ./src/digesters/app.js
          env:
            {{ template "pm2-on-premise.fullenv" .}}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      imagePullSecrets:
        - name: {{ .Values.pullSecret }}